openapi: 3.0.3
info:
  title: MDM API Integration
  version: 1.1.2
  description: Token doğrudan Authorization header'da, Bearer olmadan

servers:
  - url: https://mdm.com.tr

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

security:
  - ApiKeyAuth: []

paths:
  /auth/login:
    post:
      summary: Login to get UID
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                auth_type:
                  type: string
                domainName:
                  type: string
              required: [username, password, auth_type, domainName]
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  uniq_user_id:
                    type: string
      security: []

  /auth/mfa/verify:
    post:
      summary: MFA Verification
      operationId: verifyMfa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                otp:
                  type: string
                rememberme_enabled:
                  type: string
              required: [uid, otp, rememberme_enabled]
      responses:
        '200':
          description: Token received
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_token:
                    type: string
      security: []

  /api/v1/mdm/devices:
    get:
      summary: Get all devices (with paging)
      operationId: getDevices
      parameters:
        - in: query
          name: skip-token
          required: false
          schema:
            type: string
            description: Token used for pagination to retrieve next set of devices
      responses:
        '200':
          description: List of devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  devices:
                    type: array
                    items:
                      type: object
                      properties:
                        device_id:
                          type: string
                        serial_number:
                          type: string
                        device_name:
                          type: string
                  paging:
                    type: object
                    properties:
                      next:
                        type: string

  /api/v1/mdm/devices/{device_id}:
    put:
      summary: Update device name
      operationId: updateDevice
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - device_name
              properties:
                device_name:
                  type: string
      responses:
        '200':
          description: Device updated successfully

  /api/v1/mdm/devices/{device_id}/actions/restart:
    post:
      summary: Restart a device
      operationId: restartDevice
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device restart initiated

  /api/v1/mdm/devices/{device_id}/actions/shutdown:
    post:
      summary: Shutdown a device
      operationId: shutdownDevice
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device shutdown initiated
